### ISSUE TITLE
Console log should be optional

### ISSUE THREAD

**Issue by albertc180** [peterforgacs/ffmpeg-normalize#2]
Works great, although logging process in console should be optional as debug mode - it makes a little mess in console :)

**Comment by peterforgacs** [comment]
Hello, thanks for the feedback!
It should not be hard to implement, when i have a free weekend i ll look into it.

**Comment by peterforgacs** [comment]
Disabled console log by default.
It can be still enabled with setting the verbose parameter to true.

https://github.com/peterforgacs/ffmpeg-normalize/commit/7c03bcf319de9ba201227d9c8179998e95d169fb
